Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@same'

Options:
 test-before-installing: True
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
 enable-lsan: True
 cppcheck-arguments: '--enable=warning,performance,portability,style --suppress-xml=cppcheck-suppressions.xml'
